# Generated by Django 4.2.8 on 2023-12-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DpuAsKcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REC_TYPE', models.CharField(max_length=1)),
                ('SLIP_TYPE', models.CharField(max_length=1)),
                ('ST_ID', models.CharField(max_length=255)),
                ('CUST_ID', models.IntegerField()),
                ('TotalFileRecord', models.IntegerField()),
                ('FlagEdited', models.CharField(max_length=1)),
                ('MType', models.CharField(max_length=1)),
                ('RecordingDate', models.DateField()),
                ('SHIFT', models.CharField(max_length=1)),
                ('FAT', models.FloatField()),
                ('FAT_UNIT', models.CharField(max_length=1)),
                ('SNF', models.FloatField()),
                ('SNF_UNIT', models.CharField(max_length=1)),
                ('CLR', models.FloatField()),
                ('CLR_UNIT', models.CharField(max_length=1)),
                ('WATER', models.FloatField()),
                ('WATER_UNIT', models.CharField(max_length=1)),
                ('QT', models.FloatField()),
                ('QT_UNIT', models.CharField(max_length=1)),
                ('RATE', models.FloatField()),
                ('Amount', models.FloatField()),
                ('CAmount', models.FloatField()),
                ('CSR_NO', models.IntegerField()),
                ('CREV', models.IntegerField()),
                ('END_TAG', models.CharField(max_length=1)),
                ('dpuid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RateTableAlls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RateTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
    ]
