# Generated by Django 4.2.7 on 2023-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=12)),
                ('Dpuid', models.CharField(blank=True, max_length=12)),
                ('Society', models.CharField(max_length=12)),
                ('Mobile', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
