# Generated by Django 4.2.8 on 2023-12-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='END_TAG',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drec',
            name='MType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SHIFT',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SLIP_TYPE',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.CharField(max_length=10),
        ),
    ]
