# Generated by Django 4.2.8 on 2024-01-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='id',
        ),
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.CharField(blank=True, default='', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
        ),
    ]
