# Generated by Django 4.2.7 on 2023-12-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dpu',
        ),
    ]
