# Generated by Django 4.2.9 on 2024-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='st_id',
            field=models.CharField(max_length=50),
        ),
    ]
