# Generated by Django 4.2.9 on 2024-02-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customer_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpus', to='common.dpu'),
        ),
    ]
