# Generated by Django 4.2.8 on 2024-01-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_drec_id_alter_drec_st_id_alter_drec_dpuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
        ),
    ]
