# Generated by Django 4.2.8 on 2023-12-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_drec_end_tag_alter_drec_mtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
        ),
    ]
