# Generated by Django 4.2.9 on 2024-01-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_drec_mtype_alter_drec_shift_alter_drec_st_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
