# Generated by Django 4.2.7 on 2023-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_delete_dpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='adddpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('dpuid', models.IntegerField(max_length=30)),
                ('society', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(max_length=10)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
