# Generated by Django 4.2.9 on 2024-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_drec_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drec',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='drec',
            name='RecordingTime',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
