# Generated by Django 4.2.9 on 2024-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_drec_options_drec_recordingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpu',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
