# Generated by Django 4.2.9 on 2024-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_drec_rec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
