# Generated by Django 4.2.7 on 2023-12-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddpu',
            name='dpuid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adddpu',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
