# Generated by Django 4.2.8 on 2024-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_drec_dpuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
