# Generated by Django 4.2.9 on 2024-02-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_st_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adhaar',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_ac',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='common.dpu'),
        ),
    ]
