# Generated by Django 4.2.9 on 2024-06-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_drec_flagedited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
