# Generated by Django 4.2.9 on 2024-03-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_dpu_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpu',
            name='password',
        ),
    ]
