# Generated by Django 4.2.9 on 2024-06-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_drec_flagedited_alter_drec_rec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(choices=[(1, 'FAT/SNF/CLR Record'), (2, 'Edited FAT/SNF/CLR Data'), (3, 'Local Sell'), (4, 'Edited Local Sell'), (5, 'Dan'), (6, 'Edited Dan'), (7, 'Deduction')], default=1, max_length=255),
        ),
    ]
