# Generated by Django 4.2.9 on 2024-01-26 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
