# Generated by Django 4.2.9 on 2024-02-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_customerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerList', to='common.dpu'),
        ),
    ]
