# Generated by Django 4.2.9 on 2024-01-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_config_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='date_created',
        ),
    ]
