# Generated by Django 4.2.8 on 2024-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_drec_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='MType',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SHIFT',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
