# Generated by Django 4.2.9 on 2024-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_delete_customerlist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='common_cust_user_id_b22302_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['st_id'], name='common_cust_st_id_i_c76edb_idx'),
        ),
    ]
