# Generated by Django 4.2.9 on 2024-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_config_st_id_config_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='text_data',
            new_name='text_payload',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='config',
            name='st_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
