# Generated by Django 4.2.7 on 2023-12-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_employee_status_alter_employee_emp_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
