# Generated by Django 4.2.9 on 2024-03-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
