# Generated by Django 4.2.8 on 2024-01-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_drec_mtype_alter_drec_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='drec',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drecs', to='common.dpu'),
        ),
    ]
