# Generated by Django 4.2.9 on 2024-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_drec_rec_type_alter_drec_slip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
