# Generated by Django 4.2.9 on 2024-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_olddrecdataedited_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='RATE',
            field=models.FloatField(null=True),
        ),
    ]
