# Generated by Django 4.2.7 on 2023-12-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0008_delete_employee_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('dpu_code', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('society', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('Deactive', 'Deactive'), ('Active', 'Active')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
