# Generated by Django 4.2.9 on 2024-01-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_text_data_config_text_payload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='text_payload',
            new_name='text_data',
        ),
    ]
