# Generated by Django 4.2.9 on 2024-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_drec_rec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='FlagEdited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='REC_TYPE',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
