# Generated by Django 4.2.9 on 2024-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpu',
            name='plain_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
