# Generated by Django 4.2.8 on 2024-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_drec_id_alter_drec_st_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('adhaar', models.CharField(max_length=12)),
                ('bank_ac', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='customer_csv/')),
            ],
        ),
    ]
