# Generated by Django 4.2.9 on 2024-06-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_olddrecdataedited_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='FlagEdited',
        ),
        migrations.RemoveField(
            model_name='olddrecdataedited',
            name='FlagEdited',
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='RATE',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='ST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_drecs', to='common.dpu'),
        ),
    ]
