# Generated by Django 4.2.9 on 2024-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_drec_flagedited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='olddrecdataedited',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='RATE',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='ST_ID',
            field=models.CharField(max_length=255),
        ),
    ]
