# Generated by Django 4.2.7 on 2023-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('dpu_code', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('society', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
