# Generated by Django 4.2.9 on 2024-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_dpu_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpu',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
