# Generated by Django 4.2.9 on 2024-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_text_payload_config_text_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
