# Generated by Django 4.2.9 on 2024-02-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_customerlist_st_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerList',
        ),
    ]
