# Generated by Django 4.2.9 on 2024-01-31 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0010_alter_config_timestamp_alter_customer_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rate_tables/')),
                ('animal', models.CharField(choices=[('COW', 'COW'), ('BUFFALO', 'BUFFALO')], max_length=10)),
                ('rate_type', models.CharField(choices=[('SNF', 'SNF'), ('FAT', 'FAT'), ('CLR', 'CLR')], max_length=10)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
