# Generated by Django 4.2.9 on 2024-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_dpu_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpu',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
