# Generated by Django 4.2.7 on 2023-12-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_yourmodel_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
