# Generated by Django 4.2.9 on 2024-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_drec_flagedited_olddrecdataedited_flagedited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='RATE',
            field=models.FloatField(default=None, null=True),
        ),
    ]
