# Generated by Django 4.2.8 on 2024-01-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_customer_csv_file_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
