# Generated by Django 4.2.9 on 2024-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_drec_rec_type_alter_drec_slip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='REC_TYPE',
            field=models.CharField(max_length=255),
        ),
    ]
