# Generated by Django 4.2.9 on 2024-02-15 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_ratetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetable',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='ratetable',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='ratetable',
            name='start_date',
        ),
        migrations.AddField(
            model_name='ratetable',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
