# Generated by Django 4.2.9 on 2024-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_olddrecdataedited_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drec',
            name='FlagExpirationTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
