# Generated by Django 4.2.9 on 2024-02-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_customerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1)),
                ('start_date', models.DateField()),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='common.dpu')),
            ],
        ),
    ]
