# Generated by Django 4.2.9 on 2024-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_olddrecdataedited_rec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
