# Generated by Django 4.2.8 on 2024-01-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
