# Generated by Django 4.2.9 on 2024-03-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_dpu_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpu',
            name='password',
        ),
    ]
