# Generated by Django 4.2.9 on 2024-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_ratetable_animal_ratetable_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratetable',
            name='csv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='file',
            field=models.FileField(upload_to='rate_tables/%Y/%m/%d/'),
        ),
    ]
