# Generated by Django 4.2.8 on 2024-01-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=255)),
                ('MOBILE', models.CharField(max_length=15)),
                ('ADHHAR', models.CharField(max_length=12)),
                ('BANK_AC', models.CharField(max_length=25)),
                ('IFSC', models.CharField(max_length=15)),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu')),
            ],
        ),
    ]
