# Generated by Django 4.2.9 on 2024-06-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_drec_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drecs', to='common.dpu'),
        ),
    ]
