# Generated by Django 4.2.8 on 2024-01-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ADHHAR',
            new_name='adhaar',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='BANK_AC',
            new_name='bank_ac',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CUST_ID',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='IFSC',
            new_name='ifsc',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='MOBILE',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dpu',
        ),
    ]
