# Generated by Django 4.2.8 on 2023-12-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
