# Generated by Django 4.2.9 on 2024-02-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_ratetable_csv_date_alter_ratetable_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetable',
            name='csv_date',
        ),
    ]
