# Generated by Django 4.2.8 on 2023-12-11 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0015_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('dpu_id', models.CharField(max_length=50, unique=True)),
                ('society', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
