# Generated by Django 4.2.9 on 2024-05-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
