# Generated by Django 4.2.8 on 2024-01-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_rename_adhhar_customer_adhaar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
