# Generated by Django 4.2.9 on 2024-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_ratetable_csv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetable',
            name='file',
            field=models.FileField(upload_to='rate_tables/'),
        ),
    ]
