# Generated by Django 4.2.8 on 2023-12-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DREC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REC_TYPE', models.CharField(max_length=100)),
                ('SLIP_TYPE', models.CharField(max_length=100)),
                ('ST_ID', models.CharField(max_length=100)),
                ('CUST_ID', models.IntegerField()),
                ('TotalFileRecord', models.IntegerField()),
                ('FlagEdited', models.CharField(max_length=100)),
                ('MType', models.CharField(max_length=100)),
                ('RecordingDate', models.DateField()),
                ('SHIFT', models.CharField(max_length=100)),
                ('FAT', models.FloatField()),
                ('FAT_UNIT', models.CharField(max_length=100)),
                ('SNF', models.FloatField()),
                ('SNF_UNIT', models.CharField(max_length=100)),
                ('CLR', models.FloatField()),
                ('CLR_UNIT', models.CharField(max_length=100)),
                ('WATER', models.FloatField()),
                ('WATER_UNIT', models.CharField(max_length=100)),
                ('QT', models.FloatField()),
                ('QT_UNIT', models.CharField(max_length=100)),
                ('RATE', models.FloatField()),
                ('Amount', models.FloatField()),
                ('CAmount', models.FloatField()),
                ('CSR_NO', models.IntegerField()),
                ('CREV', models.IntegerField()),
                ('END_TAG', models.CharField(max_length=100)),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drecs', to='common.dpu')),
            ],
        ),
    ]
