# Generated by Django 4.2.8 on 2024-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DREC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REC_TYPE', models.CharField(max_length=1)),
                ('SLIP_TYPE', models.CharField(max_length=1)),
                ('ST_ID', models.CharField(max_length=50)),
                ('CUST_ID', models.IntegerField()),
                ('TotalFileRecord', models.IntegerField()),
                ('FlagEdited', models.CharField(max_length=1)),
                ('MType', models.CharField(max_length=1)),
                ('RecordingDate', models.DateField()),
                ('SHIFT', models.CharField(max_length=1)),
                ('FAT', models.FloatField()),
                ('FAT_UNIT', models.CharField(max_length=1)),
                ('SNF', models.FloatField()),
                ('SNF_UNIT', models.CharField(max_length=1)),
                ('CLR', models.FloatField()),
                ('CLR_UNIT', models.CharField(max_length=1)),
                ('WATER', models.FloatField()),
                ('WATER_UNIT', models.CharField(max_length=1)),
                ('QT', models.FloatField()),
                ('QT_UNIT', models.CharField(max_length=1)),
                ('RATE', models.FloatField()),
                ('Amount', models.FloatField()),
                ('CAmount', models.FloatField()),
                ('CSR_NO', models.IntegerField()),
                ('CREV', models.IntegerField()),
                ('END_TAG', models.CharField(max_length=1)),
                ('dpuid', models.CharField(max_length=50)),
            ],
        ),
    ]
