# Generated by Django 4.2.8 on 2023-12-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpuData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REC_TYPE', models.CharField(max_length=1)),
                ('SLIP_TYPE', models.CharField(max_length=1)),
                ('ST_ID', models.CharField(max_length=10)),
                ('CUST_ID', models.IntegerField()),
                ('TotalFileRecord', models.IntegerField()),
                ('FlagEdited', models.CharField(max_length=1)),
            ],
        ),
    ]
