# Generated by Django 4.2.9 on 2024-06-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_olddrecdataedited_original_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddrecdataedited',
            name='original_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_records', to='common.drec'),
        ),
    ]
