# Generated by Django 4.2.8 on 2023-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_drec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='dpu',
        ),
        migrations.AddField(
            model_name='drec',
            name='dpuid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
