# Generated by Django 4.2.8 on 2023-12-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_drec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='id',
        ),
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
