# Generated by Django 4.2.8 on 2023-12-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DREC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50)),
                ('flag_edited', models.CharField(max_length=1)),
                ('m_type', models.CharField(max_length=1)),
                ('recording_date', models.DateField()),
                ('shift', models.CharField(max_length=1)),
                ('fat', models.FloatField()),
                ('fat_unit', models.CharField(max_length=1)),
                ('snf', models.FloatField()),
                ('snf_unit', models.CharField(max_length=1)),
                ('clr', models.FloatField()),
                ('clr_unit', models.CharField(max_length=1)),
                ('water', models.FloatField()),
                ('water_unit', models.CharField(max_length=1)),
                ('qt', models.FloatField()),
                ('qt_unit', models.CharField(max_length=1)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('camount', models.FloatField()),
                ('csr_no', models.IntegerField()),
                ('crev', models.IntegerField()),
                ('end_tag', models.CharField(max_length=1)),
                ('dpuid', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu')),
            ],
        ),
    ]
