# Generated by Django 4.2.9 on 2024-05-19 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_questions_st_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpu',
            name='zone',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dpu',
            name='dpu_user',
            field=models.IntegerField(),
        ),
    ]
