# Generated by Django 4.2.8 on 2023-12-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_dpudata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
