# Generated by Django 4.2.8 on 2023-12-30 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DREC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REC_TYPE', models.CharField(blank=True, default='', max_length=255)),
                ('SLIP_TYPE', models.IntegerField(default=None, null=True)),
                ('ST_ID', models.CharField(blank=True, default='', max_length=255)),
                ('CUST_ID', models.IntegerField(default=None, null=True)),
                ('TotalFileRecord', models.IntegerField(default=None, null=True)),
                ('FlagEdited', models.CharField(blank=True, default='', max_length=255)),
                ('MType', models.IntegerField(default=None, null=True)),
                ('RecordingDate', models.DateField(default=None, null=True)),
                ('SHIFT', models.IntegerField(default=None, null=True)),
                ('FAT', models.FloatField(default=None, null=True)),
                ('FAT_UNIT', models.CharField(blank=True, default='', max_length=255)),
                ('SNF', models.FloatField(default=None, null=True)),
                ('SNF_UNIT', models.CharField(blank=True, default='', max_length=255)),
                ('CLR', models.FloatField(default=None, null=True)),
                ('CLR_UNIT', models.CharField(blank=True, default='', max_length=255)),
                ('WATER', models.FloatField(default=None, null=True)),
                ('WATER_UNIT', models.CharField(blank=True, default='', max_length=255)),
                ('QT', models.FloatField(default=None, null=True)),
                ('QT_UNIT', models.CharField(blank=True, default='', max_length=255)),
                ('RATE', models.FloatField(default=None, null=True)),
                ('Amount', models.FloatField(default=None, null=True)),
                ('CAmount', models.FloatField(default=None, null=True)),
                ('CSR_NO', models.IntegerField(default=None, null=True)),
                ('CREV', models.IntegerField(default=None, null=True)),
                ('END_TAG', models.CharField(blank=True, default='', max_length=255)),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu')),
            ],
        ),
    ]
