# Generated by Django 4.2.8 on 2023-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_drec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='CLR_UNIT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='END_TAG',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FAT_UNIT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='MType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='QT_UNIT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SHIFT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SLIP_TYPE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SNF_UNIT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drec',
            name='WATER_UNIT',
            field=models.CharField(max_length=100),
        ),
    ]
