# Generated by Django 4.2.9 on 2024-06-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_olddrecdataedited_original_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olddrecdataedited',
            name='original_record',
        ),
    ]
