# Generated by Django 4.2.9 on 2024-05-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_dpu_zone_alter_dpu_dpu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpu',
            name='select_dpu',
            field=models.CharField(choices=[('DPMCU', 'DPMCU'), ('BMC', 'BMC')], default='DPMCU', max_length=5),
        ),
    ]
