# Generated by Django 4.2.8 on 2023-12-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_drec_dpu_drec_dpuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
        ),
    ]
