# Generated by Django 4.2.8 on 2024-01-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('adhaar', models.CharField(max_length=12)),
                ('bank_account', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=15)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu')),
            ],
        ),
    ]
