# Generated by Django 4.2.9 on 2024-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_olddrecdataedited_original_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddrecdataedited',
            name='old_drec',
            field=models.IntegerField(null=True),
        ),
    ]
