# Generated by Django 4.2.8 on 2023-12-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_drec_dpuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.CharField(max_length=255),
        ),
    ]
