# Generated by Django 4.2.9 on 2024-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_dpu_select_dpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='drec',
            name='RID',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
