# Generated by Django 4.2.9 on 2024-02-15 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0019_ratetable_csv_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratetable',
            unique_together={('user', 'file')},
        ),
    ]
