# Generated by Django 4.2.8 on 2024-01-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_customerupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerupload',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='customer_csv/'),
        ),
    ]
