# Generated by Django 4.2.8 on 2023-12-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DateTimeRecord',
        ),
    ]
