# Generated by Django 4.2.9 on 2024-06-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_olddrecdataedited_old_drec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olddrecdataedited',
            old_name='old_drec',
            new_name='new_drec',
        ),
    ]
