# Generated by Django 4.2.8 on 2024-01-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_customerupload_csv_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUpload',
        ),
    ]
