# Generated by Django 4.2.8 on 2024-01-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_customer_ac_customer_adhhar_customer_bank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
