# Generated by Django 4.2.9 on 2024-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_drec_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='RID',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
