# Generated by Django 4.2.9 on 2024-02-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_ratetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratetable',
            unique_together=set(),
        ),
    ]
