# Generated by Django 4.2.9 on 2024-06-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_dpu_check_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpu',
            name='check_options',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
