# Generated by Django 4.2.8 on 2024-01-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0021_delete_customerupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('adhaar', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.dpu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
