# Generated by Django 4.2.8 on 2024-01-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
        ),
    ]
