# Generated by Django 4.2.9 on 2024-02-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_ratetable_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetable',
            name='animal',
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
