# Generated by Django 4.2.8 on 2024-01-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_drec_dpuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CLR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CLR_UNIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CREV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CSR_NO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CUST_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='END_TAG',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FAT_UNIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='MType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='QT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='QT_UNIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='RATE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='RecordingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SHIFT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SLIP_TYPE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SNF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SNF_UNIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='TotalFileRecord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='WATER',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='WATER_UNIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='dpuid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
        ),
    ]
