# Generated by Django 4.2.9 on 2024-01-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='csv_file',
            field=models.FileField(default=1, upload_to='customer_csv/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='adhaar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ifsc',
            field=models.CharField(max_length=11),
        ),
    ]
