# Generated by Django 4.2.9 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_remove_ratetable_animal_alter_ratetable_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratetable',
            name='animal',
            field=models.CharField(blank=True, choices=[('C', 'Cow'), ('B', 'Buffalo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('snf', 'SNF'), ('clr', 'CLR'), ('fat', 'FAT')], max_length=10, null=True),
        ),
    ]
