# Generated by Django 4.2.9 on 2024-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_customer_csv_file_alter_customer_adhaar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adhaar',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='st_id',
            field=models.CharField(max_length=50),
        ),
    ]
