# Generated by Django 4.2.9 on 2024-02-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_ratetable_animal_alter_ratetable_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('SNF', 'SNF'), ('CLR', 'CLR'), ('FAT', 'FAT')], max_length=10, null=True),
        ),
    ]
