# Generated by Django 4.2.8 on 2024-01-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_drec_amount_alter_drec_camount_alter_drec_clr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='dpuid',
        ),
        migrations.AddField(
            model_name='drec',
            name='dpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.dpu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drec',
            name='Amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CAmount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CLR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CLR_UNIT',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CREV',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CSR_NO',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='CUST_ID',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='END_TAG',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FAT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FAT_UNIT',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='FlagEdited',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='MType',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='QT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='QT_UNIT',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='RATE',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='REC_TYPE',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='RecordingDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SHIFT',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SLIP_TYPE',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SNF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='SNF_UNIT',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='ST_ID',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drec',
            name='TotalFileRecord',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='WATER',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drec',
            name='WATER_UNIT',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
