# Generated by Django 4.2.8 on 2024-01-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_remove_drec_dpuid_drec_dpu_alter_drec_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='dpu',
        ),
        migrations.AddField(
            model_name='drec',
            name='dpuid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.dpu', to_field='dpu_id'),
            preserve_default=False,
        ),
    ]
