# Generated by Django 4.2.9 on 2024-02-17 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_ratetable_rate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratetable',
            old_name='uploaded_at',
            new_name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='ratetable',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='ratetable',
            name='csv_date',
        ),
        migrations.RemoveField(
            model_name='ratetable',
            name='file',
        ),
        migrations.AddField(
            model_name='ratetable',
            name='animal_type',
            field=models.CharField(choices=[('B', 'Buffalo'), ('C', 'Cow')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratetable',
            name='csv_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='rate_table_csv/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratetable',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(choices=[('snf', 'SNF'), ('clr', 'CLR'), ('fat', 'FAT')], max_length=3),
        ),
    ]
