# Generated by Django 4.2.9 on 2024-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_remove_customer_adhaar_remove_customer_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='related_to_user',
            field=models.BooleanField(default=True),
        ),
    ]
