# Generated by Django 4.2.9 on 2024-06-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_olddrecdatadeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REC_TYPE', models.CharField(default=None, max_length=255, null=True)),
                ('SLIP_TYPE', models.IntegerField(choices=[(1, 'FAT/SNF/CLR Record'), (2, 'Edited FAT/SNF/CLR Data'), (3, 'Local Sell'), (4, 'Edited Local Sell'), (5, 'Dan'), (6, 'Edited Dan'), (7, 'Deduction')], default=1)),
                ('CUST_ID', models.IntegerField(default=None, null=True)),
                ('TotalFileRecord', models.IntegerField(default=None, null=True)),
                ('FlagEdited', models.CharField(blank=True, default='', max_length=10)),
                ('MType', models.CharField(default=None, max_length=255, null=True)),
                ('RecordingDate', models.DateField(default=None, null=True)),
                ('RecordingTime', models.CharField(default='0000', max_length=255)),
                ('SHIFT', models.CharField(default=None, max_length=255, null=True)),
                ('QT', models.FloatField(default=None, null=True)),
                ('QT_UNIT', models.CharField(blank=True, default='', max_length=255)),
                ('RATE', models.FloatField(default=None, null=True)),
                ('Amount', models.FloatField(default=None, null=True)),
                ('CAmount', models.FloatField(default=None, null=True)),
                ('CSR_NO', models.IntegerField(default=None, null=True)),
                ('CREV', models.IntegerField(default=None, null=True)),
                ('END_TAG', models.CharField(blank=True, default='', max_length=255)),
                ('dpuid', models.CharField(blank=True, default='', max_length=255)),
                ('RID', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_sells', to='common.dpu')),
            ],
        ),
    ]
