# Generated by Django 4.2.8 on 2024-01-15 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_remove_drec_dpu_drec_dpuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpu',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
