# Generated by Django 4.2.9 on 2024-02-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_rename_uploaded_at_ratetable_date_uploaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratetable',
            old_name='animal_type',
            new_name='animal',
        ),
        migrations.RemoveField(
            model_name='ratetable',
            name='date_uploaded',
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='csv_file',
            field=models.FileField(upload_to='rate_csv/'),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
