# Generated by Django 4.2.9 on 2024-02-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_rename_animal_type_ratetable_animal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateTable',
        ),
    ]
