# Generated by Django 4.2.9 on 2024-01-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_remove_customer_related_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='related_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='end_range',
            field=models.IntegerField(),
        ),
    ]
