# Generated by Django 4.2.9 on 2024-06-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_drec_delete_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drec',
            name='delete_at',
        ),
    ]
