# Generated by Django 4.2.9 on 2024-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_remove_drec_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drec',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
    ]
