# Generated by Django 4.2.9 on 2024-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_ratetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratetable',
            name='animal_code',
            field=models.CharField(choices=[('B', 'Buffalo'), ('C', 'Cow')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
