# Generated by Django 4.2.9 on 2024-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_customer_related_to_user_alter_customer_end_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='related_to_user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='csv_file',
            field=models.FileField(upload_to='csv_files/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='st_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_range',
            field=models.IntegerField(),
        ),
    ]
