# Generated by Django 4.2.9 on 2024-02-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_ratetable_animal_code_ratetable_rate_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateTable',
        ),
    ]
