# Generated by Django 4.2.9 on 2024-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_remove_customer_related_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='end_range',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_range',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
