# Generated by Django 4.2.9 on 2024-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_remove_drec_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drec',
            name='SLIP_TYPE',
            field=models.IntegerField(choices=[(1, 'FAT/SNF/CLR Record'), (2, 'Edited FAT/SNF/CLR Data'), (3, 'Local Sell'), (4, 'Edited Local Sell'), (5, 'Dan'), (6, 'Edited Dan'), (7, 'Deduction'), (9, 'Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='localsell',
            name='SLIP_TYPE',
            field=models.IntegerField(choices=[(1, 'FAT/SNF/CLR Record'), (2, 'Edited FAT/SNF/CLR Data'), (3, 'Local Sell'), (4, 'Edited Local Sell'), (5, 'Dan'), (6, 'Edited Dan'), (7, 'Deduction'), (9, 'Delete')], default=1),
        ),
    ]
