# Generated by Django 4.2.9 on 2024-01-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_alter_customer_end_range_alter_customer_start_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='end_range',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='st_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_range',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
