# Generated by Django 4.2.9 on 2024-01-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_customer_end_range_alter_customer_st_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='end_range',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_range',
        ),
    ]
