# Generated by Django 4.2.9 on 2024-02-18 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_ratetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetable',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='ratetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratetable',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='animal_type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(max_length=3),
        ),
    ]
