# Generated by Django 4.2.9 on 2024-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_remove_customer_end_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='downloaded_cust_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='end_range',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='start_range',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
