# Generated by Django 4.2.9 on 2024-02-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_remove_ratetable_date_uploaded_ratetable_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetable',
            name='animal_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='rate_type',
            field=models.CharField(max_length=100),
        ),
    ]
