# Generated by Django 4.2.9 on 2024-01-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_customer_downloaded_cust_id_customer_end_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='downloaded_cust_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='end_range',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_range',
        ),
    ]
