# Generated by Django 4.2.9 on 2024-01-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_remove_customer_downloaded_cust_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50)),
                ('text_file', models.FileField(upload_to='text_files/')),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_files', to='common.dpu')),
            ],
        ),
    ]
