# Generated by Django 4.2.9 on 2024-01-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_textfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='st_id',
        ),
    ]
