# Generated by Django 4.2.9 on 2024-01-24 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_textfile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='text_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='dpu',
        ),
        migrations.AddField(
            model_name='textfile',
            name='st_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
