# Generated by Django 4.2.9 on 2024-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_rename_text_file_textfile_file_remove_textfile_dpu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='upload_date',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='textfile',
            name='st_id',
            field=models.CharField(max_length=50),
        ),
    ]
