# Generated by Django 4.2.9 on 2024-01-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_rename_upload_date_textfile_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='timestamp',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='st_id',
        ),
        migrations.AddField(
            model_name='textfile',
            name='ST_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='text_files', to='common.dpu'),
            preserve_default=False,
        ),
    ]
