# Generated by Django 4.2.9 on 2024-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_rename_upload_date_textfile_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='timestamp',
            new_name='upload_date',
        ),
        migrations.AlterField(
            model_name='textfile',
            name='st_id',
            field=models.CharField(max_length=255),
        ),
    ]
