# Generated by Django 4.2.9 on 2024-01-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_rename_timestamp_textfile_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='ST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textfiles', to='common.dpu'),
        ),
    ]
