# Generated by Django 4.2.9 on 2024-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_alter_textfile_st_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='ST_ID',
        ),
        migrations.AddField(
            model_name='textfile',
            name='st_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
