# Generated by Django 4.2.9 on 2024-01-24 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_remove_textfile_st_id_textfile_st_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
