# Generated by Django 4.2.9 on 2024-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_remove_textfile_file_textfile_text_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='st_id',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='text_data',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='user',
        ),
        migrations.AddField(
            model_name='textfile',
            name='text_field_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
