# Generated by Django 4.2.9 on 2024-01-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0047_remove_textfile_st_id_remove_textfile_text_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='text_field_name',
        ),
        migrations.AddField(
            model_name='textfile',
            name='st_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfile',
            name='text_data',
            field=models.CharField(default=1, max_length=500000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
