# Generated by Django 4.2.5 on 2023-11-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
