# Generated by Django 4.2.5 on 2023-12-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
