# Generated by Django 4.2.7 on 2023-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('dpu_id', models.CharField(blank=True, max_length=50)),
                ('society', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
    ]
