# Generated by Django 4.2.7 on 2023-12-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_dpu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DPU',
        ),
    ]
